#!/bin/bash
# -*-sh-*-

TEST_LOGS=""
MAKEFLAGS=""
status=0

source ./TEST_ENV         || exit 1
source ./common/functions || exit 1

cd runtimes/libomp        || exit 1

export BATS_JUNIT_CLASS=LIBOMP

# bootstrap the local autotools project

./bootstrap || exit 1

for compiler in $COMPILER_FAMILIES ; do

    echo " "
    echo " "
    echo "----------------------------------------------------------"
    echo "User Libraries: LIBOMP tests: $compiler"
    echo "----------------------------------------------------------"

    module purge                || exit 1
    module load $compiler       || exit 1
    module load libomp          || exit 1

    ./configure                 || exit 1
    make clean >& /dev/null     || exit 1
    make -k check               || status=1

    save_logs_compiler_family tests $compiler
    save_logs_compiler_family tests/ohpc_module $compiler

    make distclean >& /dev/null

done

exit ${status}
